// 
// ----------------------------------------------------------
// ----------------------------------------------------------
// This file was automatically generated by the OpenCourse   
// Agnostic Data Access tool, please do not edit this file   
// directly since it will be overwritten every time the tool 
// is run.
// 
// This file was generated on 5/16/2008 1:54:27 AM
// ----------------------------------------------------------
// ----------------------------------------------------------
//
namespace SND.KQ.DAL.FRAS
{
    
    
    public enum CommandEnumeration
    {

        GetUserInfo = 0,

        GetDevInfo = 1,

        GetCopyData = 2,

        GetFirstWorkLog=3,

        GetAccessLogByUserId=4,

        GetAccessLogByUserIdAndDevNum=5,

        GetWorkDurationByUserId=6,
        GetWorkDurationByUserIdAndDevNum=7,

        UpdateWorkDurationRecord=8,

        UpdateWorkDurationRecordAndBak1 = 9,

        AddWorkDurationRecord=10,

        GetPreRostInfoByUserId=11,

        GetWorkDurationByUserId2=12,

        GetRostingById=13,

        GetUserRostingByUserId=14,

        GetFirstWorkDuration =15,

        AddAccessLog=16,

        GetAllRostInfo=17,

        GetWorkDurationByRosteId = 18,
        
        UpdateWorkDurations=19,

        GetUserWorkDuration=20,

        GetDeptInfo = 21,

        GetUserInfoByName = 22,

        GetUserInfoById = 23,

        GetRankInfo = 24,

        UpdateUserInfoFeatureInfo = 25,

        UpdateUserCardInfo = 26,

        CreatUserFeature = 27,

        CreatUserCard = 28,

        CreatUserInfo = 29,

        GetCardInfoByUserId=30,

    }
}
