// 
// ----------------------------------------------------------
// ----------------------------------------------------------
// This file was automatically generated by the OpenCourse   
// Agnostic Data Access tool, please do not edit this file   
// directly since it will be overwritten every time the tool 
// is run.
// 
// This file was generated on 5/16/2008 1:54:27 AM
// ----------------------------------------------------------
// ----------------------------------------------------------
//
namespace SND.KQ.DAL.Well
{
    
    
    public enum CommandEnumeration
    {

        GetWellInfo = 0,

        

    }
}
